name: Build and Push Docker image to GitHub Package

on: [push]

env:
  DOCKER_IMAGE_NAME: communitization-bot
  DOCKER_IMAGE_TAG: latest
  DOCKERFILE_PATH: Dockerfile
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  REPOSITORY_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Docker CLI
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ env.GITHUB_USERNAME }}
        password: ${{ env.GITHUB_TOKEN }}

    - name: downcase GITHUB_USERNAME
      run: echo "USERNAME=${GITHUB_USERNAME,,}" >>${GITHUB_ENV}

    - name: Build Docker image
      run: docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG -f $DOCKERFILE_PATH .

    - name: Tag Docker image
      run: docker tag ghcr.io/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG ${{ env.USERNAME }}/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

    - name: Push Docker image
      run: docker push ghcr.io/${{ env.USERNAME }}/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
